[32m2024-03-04 18:30:27 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0c489112-ea48-4de2-88ca-62ad2fee2579 - 50124 - LOGS_CAPTURED - Started capturing logs in process (pid: 50124).
[32m2024-03-04 18:30:27 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0c489112-ea48-4de2-88ca-62ad2fee2579 - 50124 - trainLudwigModelRegression - STEP_START - Started execution of step "trainLudwigModelRegression".
[32m2024-03-04 18:30:27 +0100[0m - dagster - [34mINFO[0m - __ASSET_JOB - 0c489112-ea48-4de2-88ca-62ad2fee2579 - trainLudwigModelRegression - Trainin Running
[32m2024-03-04 18:30:27 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 0c489112-ea48-4de2-88ca-62ad2fee2579 - 50124 - trainLudwigModelRegression - STEP_FAILURE - Execution of step "trainLudwigModelRegression" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "trainLudwigModelRegression"::

TypeError: can only concatenate str (not "NoneType") to str

Stack Trace:
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelthomas/Development/MLOPS/my-dagster-project/quickstart_etl/assets/prod-pipeline.py", line 133, in trainLudwigModelRegression
    data_file = "data_"+stock_name+".csv"
                ~~~~~~~^~~~~~~~~~~
[0m
